import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'

import { Bruno_Ace_SC } from 'next/font/google';

const bruno = Bruno_Ace_SC({
  subsets: ['latin'],
  weight: '400', // Bruno Ace SC only has one weight
  display: 'swap',
  variable: '--font-bruno', // Optional but useful for custom CSS vars
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
